### ISSUE TITLE
The requested resource / was not found on this server.

### ISSUE THREAD

**Issue by techionltd** [tenKinetic/Knerve#6]
If using index.htm as the default page, get the error "The requested resource / was not found on this server."
Changelog states : -
"1.0.9:
https://github.com/tenKinetic/Knerve/releases/tag/v1.0.9
Fixed path error for static files with query strings.
_**Added default file support for index.php, index.html and index.htm.**_
Extended SSL certificate for 10 years."

Is this an undocumented setting ?

**Comment by tenKinetic** [comment]
i don't seem to have this issue myself, I wonder if your logs have lines such as this?:

2019-07-22 11:06:18: INFO: search for /xxx/index.php
2019-07-22 11:06:18: INFO: search for /xxx/index.html
2019-07-22 11:06:18: INFO: handle /xxx/index.htm

Which version are you actually running?

**Comment by techionltd** [comment]
running version 1.1.1

Initial error message on startup :-
_Uncaught Exception:
TypeError: Cannot read property 'length' of null
    at fs.readFile (/Applications/Knerve.app/Contents/Resources/app.asar/build/main.min.js:3:11336)
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)_

nothing in logs relating to index.htm/html/php

_2019-07-19 10:06:42: ERROR: Error reading modified settings file: Error: ENOENT: no such file or directory, open '/Users/default/Library/Application Support/Knerve/knerve.json'
2019-07-19 10:06:44: INFO: Loaded settings:
2019-07-19 10:06:44: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[]}
2019-07-19 10:06:44: INFO: DNS server started with config: {"bin":"/Applications/Knerve.app/Contents/Resources/app.asar/build/bin/pow","dstPort":80,"httpPort":20559,"dnsPort":20560,"timeout":900,"workers":2,"domains":["knerve"],"extDomains":[],"hostRoot":"/Users/default/Library/Application Support/Pow/Hosts","logRoot":"/Users/default/Library/Logs/Pow","rvmPath":"/Users/default/.rvm/scripts/rvm"}
2019-07-19 10:06:44: INFO: Bounce server running on secure port 63704
2019-07-19 10:06:44: INFO: Bounce server running on port 63705
2019-07-19 10:07:00: INFO: MySQL installation not detected
2019-07-19 10:09:25: INFO: CHECK: 127.0.0.1:64223/
2019-07-19 10:09:25: INFO: CHECK: 127.0.0.1:64223/
2019-07-19 10:09:25: INFO: CHECK: 127.0.0.1:64223/
2019-07-19 10:10:52: INFO: CHECK: 127.0.0.1:64427/
2019-07-19 10:46:15: INFO: Packet filter shut down, Anchor & Resolver removed successfully
2019-07-22 08:42:46: INFO: Loaded settings:
2019-07-22 08:42:46: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/auto-integrale.co.uk","id":"af2449f4dacb","name":"auto-integrale.co.uk"}]}
2019-07-22 08:42:46: INFO: DNS server started with config: {"bin":"/Applications/Knerve.app/Contents/Resources/app.asar/build/bin/pow","dstPort":80,"httpPort":20559,"dnsPort":20560,"timeout":900,"workers":2,"domains":["knerve"],"extDomains":[],"hostRoot":"/Users/default/Library/Application Support/Pow/Hosts","logRoot":"/Users/default/Library/Logs/Pow","rvmPath":"/Users/default/.rvm/scripts/rvm"}
2019-07-22 08:42:46: INFO: Bounce server running on secure port 51543
2019-07-22 08:42:46: INFO: Bounce server running on port 51544
2019-07-22 08:42:47: INFO: CHECK: 127.0.0.1:51542/
2019-07-22 08:42:47: INFO: CHECK: 127.0.0.1:51542/
2019-07-22 08:42:51: INFO: MySQL installation not detected
2019-07-22 08:43:50: INFO: CHECK: 127.0.0.1:51755/
2019-07-22 08:43:50: INFO: CHECK: 127.0.0.1:51755/
2019-07-22 08:43:50: INFO: CHECK: 127.0.0.1:51755/
2019-07-22 08:44:14: INFO: CHECK: 127.0.0.1:51874/
2019-07-22 08:46:02: INFO: Packet filter shut down, Anchor & Resolver removed successfully
2019-07-22 08:46:10: INFO: Loaded settings:
2019-07-22 08:46:10: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/www.knerve.test","id":"86224eab2f0c","name":"www.knerve.test"}]}
2019-07-22 08:46:11: INFO: DNS server started with config: {"bin":"/Applications/Knerve.app/Contents/Resources/app.asar/build/bin/pow","dstPort":80,"httpPort":20559,"dnsPort":20560,"timeout":900,"workers":2,"domains":["knerve"],"extDomains":[],"hostRoot":"/Users/default/Library/Application Support/Pow/Hosts","logRoot":"/Users/default/Library/Logs/Pow","rvmPath":"/Users/default/.rvm/scripts/rvm"}
2019-07-22 08:46:11: INFO: Bounce server running on secure port 52055
2019-07-22 08:46:11: INFO: Bounce server running on port 52056
2019-07-22 08:46:11: INFO: CHECK: 127.0.0.1:52054/
2019-07-22 08:46:11: INFO: CHECK: 127.0.0.1:52054/
2019-07-22 08:46:15: INFO: MySQL installation not detected
2019-07-22 08:49:14: INFO: Loaded settings:
2019-07-22 08:49:14: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/www.knerve.test","id":"86224eab2f0c","name":"www.knerve.test"}]}
2019-07-22 08:49:16: INFO: CHECK: 127.0.0.1:52289/
2019-07-22 08:50:20: INFO: Loaded settings:
2019-07-22 08:50:20: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/www.knerve.test","id":"86224eab2f0c","name":"www.knerve.test"}]}
2019-07-22 08:50:20: INFO: CHECK: 127.0.0.1:52365/
2019-07-22 08:50:25: INFO: Loaded settings:
2019-07-22 08:50:25: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/www.knerve.test","id":"86224eab2f0c","name":"www.knerve.test"}]}
2019-07-22 08:50:25: INFO: CHECK: 127.0.0.1:52374/
2019-07-22 08:50:41: INFO: Packet filter shut down, Anchor & Resolver removed successfully
2019-07-22 08:51:09: INFO: Loaded settings:
2019-07-22 08:51:09: INFO: {"autoLaunch":false,"mysql":{"enabled":false,"start":"/usr/local/mysql/bin/mysqld_safe --user=root","status":"/usr/local/mysql/bin/mysqladmin version","stop":"/usr/local/mysql/support-files/mysql.server stop"},"sites":[{"directory":"/Users/default/Documents/websites/www.knerve.test","id":"86224eab2f0c","name":"www.knerve.test"}]}
2019-07-22 08:51:10: INFO: DNS server started with config: {"bin":"/Applications/Knerve.app/Contents/Resources/app.asar/build/bin/pow","dstPort":80,"httpPort":20559,"dnsPort":20560,"timeout":900,"workers":2,"domains":["knerve"],"extDomains":[],"hostRoot":"/Users/default/Library/Application Support/Pow/Hosts","logRoot":"/Users/default/Library/Logs/Pow","rvmPath":"/Users/default/.rvm/scripts/rvm"}
2019-07-22 08:51:10: INFO: Bounce server running on secure port 52433
2019-07-22 08:51:10: INFO: Bounce server running on port 52434
2019-07-22 08:51:10: INFO: CHECK: 127.0.0.1:52431/
2019-07-22 08:51:10: INFO: CHECK: 127.0.0.1:52431/
2019-07-22 08:51:15: INFO: MySQL installation not detected_

**Comment by tenKinetic** [comment]
I think you've been seeing a symptom of another issue.
I'm hoping the 1.1.2 release will sort that out.
